### ISSUE TITLE
hi, when using the balcony branch the mouse pointer is not displayed, how do I get the mouse to display properly?

### ISSUE THREAD

**Issue by Yakumo-Yukari** [iamverysimp1e/Public-Dot-Files#95]
I can see the mouse pointer when I enter the desktop, but after a while it disappears, with other hyprland.config configurations the mouse shows up fine, which of the hyprland configurations do I need to change?

**Comment by 1amSimp1e** [comment]
Can you send me the one that works ?

**Comment by 1amSimp1e** [comment]
Thank you I fixed the Mouse and Gesture. It should work rn
